# Generated by Django 4.2.2 on 2023-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agent_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
