# Generated by Django 4.2.2 on 2023-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_company_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='task_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]