# Generated by Django 4.2.2 on 2023-07-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('service', '0003_company_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='agent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
