# Generated by Django 4.2.2 on 2023-07-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_company_agent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='agent_name',
            new_name='agent',
        ),
    ]
