# Generated by Django 4.2.2 on 2023-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_company_options_company_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='task_asses',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='task_description',
            field=models.TextField(max_length=600),
        ),
    ]
