# Generated by Django 4.2.2 on 2023-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_company_task_asses_alter_company_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='select_delivery',
            field=models.CharField(choices=[('curier', 'Curier'), ('predare ', 'Predat client'), ('dantex', 'Ridicat Dantex')], default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
