# Generated by Django 4.2.2 on 2023-08-07 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_company_select_delivery_alter_company_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='task_resolve',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='select_delivery',
            field=models.CharField(choices=[('Curier', 'Curier'), ('Predat Client ', 'predare'), ('Ridicat Dantex', 'dtx')], max_length=14),
        ),
        migrations.AlterField(
            model_name='company',
            name='select_status',
            field=models.CharField(choices=[('garantie', 'Garantie'), ('post_garantie', 'Post Garantie'), ('extern', 'Extern')], max_length=14),
        ),
    ]
